module.exports = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',

  ADD_GROUP: 'ADD_GROUP',
  REMOVE_GROUP: 'REMOVE_GROUP',
  CLICK_GROUP: 'CLICK_GROUP',

  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER'
};
